name: cacao_apps
description: "AI-powered Cacao disease detection and farm management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  flutter_secure_storage: ^9.0.0
  
  camera: ^0.11.0
  permission_handler: ^11.0.0
  flutter_map: ^6.0.0 
  latlong2: ^0.9.0

  showcaseview: ^3.0.0

  smooth_page_indicator: ^1.1.0 
  
  shared_preferences: ^2.2.2 

  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/final_cacao_disease_model1.0.tflite
    - assets/labels/labels.txt
    - assets/rules/recommendations.json

